package webserbice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-27T18:23:41.296+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "wsDataEngineForWebSite", 
                  wsdlLocation = "file:conf/hotel.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class WsDataEngineForWebSite extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "wsDataEngineForWebSite");
    public final static QName WsDataEngineForWebSiteSoap12 = new QName("http://tempuri.org/", "wsDataEngineForWebSiteSoap12");
    public final static QName WsDataEngineForWebSiteSoap = new QName("http://tempuri.org/", "wsDataEngineForWebSiteSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:conf/hotel.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsDataEngineForWebSite.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:conf/hotel.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsDataEngineForWebSite(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsDataEngineForWebSite(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDataEngineForWebSite() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WsDataEngineForWebSiteSoap
     */
    @WebEndpoint(name = "wsDataEngineForWebSiteSoap12")
    public WsDataEngineForWebSiteSoap getWsDataEngineForWebSiteSoap12() {
        return super.getPort(WsDataEngineForWebSiteSoap12, WsDataEngineForWebSiteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDataEngineForWebSiteSoap
     */
    @WebEndpoint(name = "wsDataEngineForWebSiteSoap12")
    public WsDataEngineForWebSiteSoap getWsDataEngineForWebSiteSoap12(WebServiceFeature... features) {
        return super.getPort(WsDataEngineForWebSiteSoap12, WsDataEngineForWebSiteSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WsDataEngineForWebSiteSoap
     */
    @WebEndpoint(name = "wsDataEngineForWebSiteSoap")
    public WsDataEngineForWebSiteSoap getWsDataEngineForWebSiteSoap() {
        return super.getPort(WsDataEngineForWebSiteSoap, WsDataEngineForWebSiteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDataEngineForWebSiteSoap
     */
    @WebEndpoint(name = "wsDataEngineForWebSiteSoap")
    public WsDataEngineForWebSiteSoap getWsDataEngineForWebSiteSoap(WebServiceFeature... features) {
        return super.getPort(WsDataEngineForWebSiteSoap, WsDataEngineForWebSiteSoap.class, features);
    }

}
